### ISSUE TITLE
only one language

### ISSUE THREAD

**Issue by OrionRandD** [dakra/dmacs#2]
Your snippet is great 

yas-auto-next (yas-completing-read "Language: " (mapcar 'car org-babel-load-languages

But I only get emacs-lisp for autocompletion and I have more babel languages enabled in my init.el.
How can I get more autocomplete options in the minibuffer?
Thx a lot

**Comment by dakra** [comment]
What is the value of `org-babel-load-languages` (You can check with `M-x describe-variable`)?
The unaltered original value is only `emacs-lisp`,
E.g. I load a lot of languages in my config [here](https://github.com/dakra/dmacs/blob/master/init.org#org-babel).

**Comment by OrionRandD** [comment]
Hi,
Thx a lot for the hit.
I have configured the variables
Cheers!
