### ISSUE TITLE
git@github.com: Permission denied (publickey). fatal: Could not read from remote repository.

### ISSUE THREAD

**Issue by DaxGoon** [dakra/dmacs#3]
Getting the following error:
```
Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:emacscollective/borg.git' into submodule path '~/dmacs/lib/borg' failed
make: *** [bootstrap-borg] Error 128
```

**Comment by Kaligule** [comment]
I do not know what you tried to do, but have you tried cloning via http (instead of ssh)?

**Comment by dakra** [comment]
@DaxGoon what exactly did you do to get this error?

I would also like to point out that this is not really a starter-kit like spacemacs/doom etc.
It's cluttered with my personal stuff all over the place.
I also have quite a bunch of uncommited stuff
on my machine, I'm not even sure if everything works without it.

It's probably better to just use this repo to copy and paste snippets from and take inspiration.

Hopefully I find the time someday to clean everything up and pull out my personal config stuff in a separate file/package.

**Comment by DaxGoon** [comment]
I get that error when I run:

`make bootstrap-borg`

I get same error on GNU/Linux (Fedora) and OSX Big Sur.

I have been testing different emacs configs because I am building my own, hence I tested this one. I do not have plans for using it other than testing (benchmarking speed of loading, use of repositories, custom lisp functions etc.). I have a few more environment/machines available I can test this on if you want to know what issues / results I get.
