### ISSUE TITLE
Load order of org packages

### ISSUE THREAD

**Issue by Thaodan** [dakra/dmacs#5]
Hey, 

After using much of your org config as a base, I noticed recent after upgrading to a newer Emacs 29 ref (29.0.50.160513-1) that the load order isn't set or wrong for some of the org-packages is wrong.

**Comment by Thaodan** [comment]
The company-backends issue was because of my modifications, I've added this org-mode-hook that cause the problem:
```emacs-lisp
(add-hook 'org-mode-hook
          (lambda ()
            ;; Automatic line-wrapping in org-mode
            ;;(auto-fill-mode 1)
            (make-local-variable 'company-backends)
            (add-to-list 'company-backends
                         '(company-capf :with company-dabbrev))

            (setq completion-at-point-functions
                  '(org-completion-symbols
                    ora-cap-filesystem))))
```
In case of such usage org should get `:after company`.

**Comment by dakra** [comment]
> In case of such usage org should get :after company.

Then org would be loaded every time you load company.
In that case I think it would be better to just put a `(require 'company)` inside the hook lambda.

**Comment by Thaodan** [comment]
Sorry forgot to reply.

> Then org would be loaded every time you load company.
> In that case I think it would be better to just put a `(require 'company)` inside the hook lambda.

That makes sense I will try.
