### ISSUE TITLE
Pdf-tools print-pdf is rundant

### ISSUE THREAD

**Issue by Thaodan** [dakra/dmacs#7]
Hey, I noticed that your print-pdf function is now redundant as there's
`pdf-misc-print-document` which also uses external commands such as hp-print.

It also works with buffers where the file isn't stored on disk e.g. pdf's opened from Gnus article buffer.

**Comment by dakra** [comment]
Thanks. Very good tip. I didn't notice :)

**Comment by Thaodan** [comment]
Remember to set `pdf-misc-print-program-executable` to `hp-print` if you
keep the old behaviour.

**Comment by dakra** [comment]
Thanks.
I saw. But actually lately I only use some proprietary printer where I send my pdfs via a web interface because cups is not really working with it.. but I don't print that much so I'm not bothered to investigate further :)

**Comment by Thaodan** [comment]
Not even ipps works? Dark times.
